
exclude:
  - LICENSE
  - CNAME
  - Gemfile
  - Gemfile.lock
  - alembic-jekyll-theme.gemspec
  - .jekyll-cache

plugins:
  - jekyll-remote-theme
  - jekyll-feed
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-mentions
  - jekyll-seo-tag
  - jekyll-redirect-from
  - jekyll-commonmark
  - jekyll-include-cache
  - jemoji

remote_theme: daviddarnes/alembic@main

title: ozmitter.github.io
description: Austin on DevOps, Programming, IT.
author: Austin

email: "austinsecure000@protonmail.com"
  
paginate: 2 # jekyll-paginate > items per page
paginate_path: blog/page:num # jekyll-paginate > blog page

collections:
  posts:
    title: Testing # Needed for Siteleaf
    output: true
    description: "Testing thoughts and ideas" # The post list page content
    feature_text: |
      Welcome to the blog
    feature_image: "https://picsum.photos/2560/600?image=866"
    
    title: Testing # Needed for Siteleaf
    output: true
    description: "Testing thoughts and ideas" # The post list page content
    feature_text: |
      feature_text: |
  <script src="https://cdn.jsdelivr.net/particles.js/2.0.0/particles.min.js"></script><script src="https://ozmitter.github.io/assets/scripts/test.js"></script>
    feature_image: "https://picsum.photos/2560/600?image=866"
    
  
    
defaults:
  -
    scope:
      path: ""
    values:
      image: "/assets/default-social-image.png" # Default image for sharing
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages

navigation_header:
- title: Greetings!
  url: /
- title: About
  url: /about.html
- title: Index
  url: /categories.html
- title: Search
  url: /search.html
- title: Contact
  url: /contact.html

navigation_footer:
- title: DevOps, Programming, IT
  url: https://www.milozzo.com/
