remote_theme: daviddarnes/alembic@main
plugins:
  - jekyll-remote-theme
  - jekyll-feed
  
title: ozmitter.github.io
description: Austin on DevOps, Programming, IT.
author: Austin

email: "austinsecure000@protonmail.com"
  
sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"

navigation_header:
- title: Greetings!
  url: /
- title: About
  url: /about.html
- title: Index
  url: /categories.html
- title: Search
  url: /search.html
- title: Contact
  url: /contact.html

navigation_footer:
- title: DevOps, Programming, IT
  url: https://www.milozzo.com/
