remote_theme: daviddarnes/alembic@main
plugins:
  - jekyll-remote-theme
  
sharing_links: # Appear at the bottom of single blog posts, add as desired. The value can be 'true' or the desired button colour
  Twitter: "#0d94e7"
  facebook: "#3B5998"

navigation_header:
- title: Greetings!
  url: /
- title: About
  url: /about.html
- title: Index
  url: /categories.html
- title: Search
  url: /search.html

navigation_footer:
- title: © milozzo.com 2022
  url: https://www.milozzo.com/
